# Generated by Django 4.0.5 on 2022-07-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
